apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-example-
spec:
  # entrypoint is the name of the template used as the starting point of the workflow
  entrypoint: ci-example
  # the 'ci-example' template accepts an parameter 'revision', with a default of 'master'.
  # this can be overridden via argo CLI (e.g. `argo submit ci.yaml -p revision=0dea2d0`)
  arguments:
    parameters:
      - name: revision
        value: master
  # a temporary volume, named workdir, will be used as a working directory
  # for this workflow. This volume is passed around from step to step.
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

  templates:
    - name: ci-example
      inputs:
        parameters:
          - name: revision
      steps:
        - - name: build
            template: build-node-example
            arguments:
              parameters:
                - name: revision
                  value: "{{inputs.parameters.revision}}"
        # the test step expands into three parallel steps running
        # different operating system images. each mounts the workdir
        # and runs the compiled binary from the build step.
        - - name: test
            template: run-hello

    - name: build-node-example
      inputs:
        parameters:
          - name: revision
        artifacts:
          - name: code
            path: /app
            git:
              repo: "{{inputs.parameters.repo}}"
              revision: "{{inputs.parameters.revision}}"
      container:
        image: node
        command: ["npm"]
        args: ["install"]
        volumeMounts:
          - name: workdir
            mountPath: /app
    - name: run-test
      container:
        image: node
        command: ["npm"]
        args: ["test"]
        volumeMounts:
          - name: workdir
            mountPath: /app